[package]
name = "egui_wgpu_backend"
version = "0.1.0"
authors = ["Nils Hasenbanck <nils@hasenbanck.de>"]
edition = "2018"
description = "Backend code to use egui with wgpu."
homepage = "https://github.com/hasenbanck/egui-wgpu-backend"
repository = "https://github.com/hasenbanck/egui-wgpu-backend"
license = "MIT OR Apache-2.0"

[dependencies]
egui = "0.2"
wgpu = "0.6"
bytemuck = "1.4"

[build-dependencies]
shaderc = "0.6"
